import { join } from 'node:path';
import { ROOT, needsAttribution, writeFormatted } from './asset-manifest.mjs';

/** One row of the attribution table. */
function row(manifest, asset) {
  const author = asset.author ?? (needsAttribution(manifest, asset) ? '**MISSING**' : '—');
  return `| ${asset.title ?? asset.id} | ${asset.license} | ${author} | [link](${asset.source}) |`;
}

/**
 * Regenerates CREDITS.md from the manifest, so attribution can never drift out
 * of sync with what is actually shipped. Edit the manifest, not this output.
 *
 * Fetched assets and assets a human has to install are listed separately, and
 * that separation is the honest part: a credits file that lists a pack nobody
 * has downloaded is claiming to ship something it does not.
 */
export async function writeCredits(manifest) {
  const fetched = manifest.assets.filter((asset) => asset.provenance !== 'local');
  const local = manifest.assets.filter((asset) => asset.provenance === 'local');

  const lines = [
    '# Credits',
    '',
    '<!-- Generated by `npm run assets:fetch`. Do not edit by hand: change',
    '     assets/manifest.json and re-run. -->',
    '',
    'Everything not listed here — the terrain, the water, the sky and every',
    'tree, cactus, rock and tuft of grass in the valley — is generated in code',
    'by this project and carries no third-party licence.',
    '',
    '## Third-party assets',
    '',
    'Fetched and pinned by `npm run assets:fetch`.',
    '',
    '| Asset | Licence | Author | Source |',
    '| --- | --- | --- | --- |',
    ...fetched.map((asset) => row(manifest, asset)),
  ];

  if (local.length > 0) {
    lines.push(
      '',
      '## Packs you install yourself',
      '',
      'These cannot be downloaded from the environment this project is built in,',
      'so they are declared here with their licence and left to a human to supply:',
      'download the pack and run `npm run assets:link -- <folder>`. Nothing here is',
      'shipped in this repository, and the scene is complete without any of it.',
      '',
      '| Asset | Licence | Author | Source |',
      '| --- | --- | --- | --- |',
      ...local.map((asset) => row(manifest, asset)),
    );
  }

  lines.push(
    '',
    '## Fonts',
    '',
    '| Font | Licence | Source |',
    '| --- | --- | --- |',
    '| Fredoka | OFL-1.1 | [Google Fonts](https://fonts.google.com/specimen/Fredoka) |',
    '',
    '## Libraries',
    '',
    '| Library | Licence | Source |',
    '| --- | --- | --- |',
    '| three.js | MIT | [threejs.org](https://threejs.org) |',
    '',
  );

  await writeFormatted(join(ROOT, 'CREDITS.md'), lines.join('\n'));
}
