import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { ROOT, needsAttribution } from './asset-manifest.mjs';

/**
 * Regenerates CREDITS.md from the manifest, so attribution can never drift out
 * of sync with what is actually shipped. Edit the manifest, not this output.
 */
export async function writeCredits(manifest) {
  const lines = [
    '# Credits',
    '',
    '<!-- Generated by `npm run assets:fetch`. Do not edit by hand: change',
    '     assets/manifest.json and re-run. -->',
    '',
    'Everything not listed here — the city layout, the road surfaces, the trees,',
    'the kart, the sky, and every sound — is generated in code by this project and',
    'carries no third-party licence.',
    '',
    '## Third-party assets',
    '',
    '| Asset | Licence | Author | Source |',
    '| --- | --- | --- | --- |',
  ];

  for (const asset of manifest.assets) {
    const author = asset.author ?? (needsAttribution(manifest, asset) ? '**MISSING**' : '—');
    lines.push(
      `| ${asset.title ?? asset.id} | ${asset.license} | ${author} | [link](${asset.source}) |`,
    );
  }

  lines.push(
    '',
    '## Fonts',
    '',
    '| Font | Licence | Source |',
    '| --- | --- | --- |',
    '| Fredoka | OFL-1.1 | [Google Fonts](https://fonts.google.com/specimen/Fredoka) |',
    '',
    '## Libraries',
    '',
    '| Library | Licence | Source |',
    '| --- | --- | --- |',
    '| three.js | MIT | [threejs.org](https://threejs.org) |',
    '',
  );

  await writeFile(join(ROOT, 'CREDITS.md'), lines.join('\n'), 'utf8');
}
